services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: chattr-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - dynamodb-data:/data

  redis:
    image: redis:7
    container_name: chattr-redis
    ports:
      - "6379:6379"

volumes:
  dynamodb-data:
